In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
list_angka = [5, 4, 9, 12, 20]
array_list = np.array(list_angka)

In [4]:
type(array_list)

numpy.ndarray

In [5]:
print(array_list)

[ 5  4  9 12 20]


In [6]:
baris1 = [1, 3, 5]
baris2 = [4, 5, 6]
baris3 = [7, 8, 9]

arr_2d = np.array([baris1, baris2, baris3])
print(arr_2d)

[[1 3 5]
 [4 5 6]
 [7 8 9]]


In [7]:
arr_2d.shape

(3, 3)

In [9]:
arr_2d_2 = np.arange(1, 8)

print(arr_2d_2)

[1 2 3 4 5 6 7]


In [10]:
arr_2d_3 = np.arange(4, 10, 2)

print(arr_2d_3)

[4 6 8]


In [13]:
arr_2d_4 = np.arange(10, 5, -1)

print(arr_2d_4)

[10  9  8  7  6]


In [14]:
ones_array = np.ones(3)

print(ones_array)

[1. 1. 1.]


In [15]:
ones_2d = np.ones((3,2))

print(ones_2d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
zeros_array = np.zeros(3)

print(zeros_array)

[0. 0. 0.]


In [17]:
zeros_2d = np.zeros((3,2))

print(zeros_2d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
eye_array = np.eye(3)

print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
eye_array = np.eye(5)

print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
random_array = np.random.rand(2, 3)

print(random_array)

[[0.74409834 0.75954622 0.20826185]
 [0.60342717 0.99672876 0.51848984]]


In [21]:
random_ar2 = np.random.randn(2, 3)

print(random_ar2)

[[-1.04262772  1.30872394  0.90344579]
 [ 0.16710077  1.13663397  0.1280985 ]]


In [23]:
random_ar3 = np.random.randint(2, 10, 4)

print(random_ar3)

[2 8 7 2]


# Reshaping Array

In [24]:
nil_random = np.random.rand(3, 4)
print(nil_random)

[[0.87199262 0.24296187 0.41655633 0.10616679]
 [0.88317983 0.95899546 0.42890005 0.63229452]
 [0.92134945 0.2460307  0.8681495  0.11411164]]


In [25]:
nil_random = nil_random.reshape(2, 6)

print(nil_random)

[[0.87199262 0.24296187 0.41655633 0.10616679 0.88317983 0.95899546]
 [0.42890005 0.63229452 0.92134945 0.2460307  0.8681495  0.11411164]]


In [26]:
nil_random2 = nil_random.reshape(6, 2)

print(nil_random2)

[[0.87199262 0.24296187]
 [0.41655633 0.10616679]
 [0.88317983 0.95899546]
 [0.42890005 0.63229452]
 [0.92134945 0.2460307 ]
 [0.8681495  0.11411164]]


In [27]:
nil = np.arange(1, 10)

print(nil)

[1 2 3 4 5 6 7 8 9]


In [28]:
print(nil[3])

4


In [29]:
print(nil[6:9])

[7 8 9]


In [30]:
print(nil[3:])

[4 5 6 7 8 9]


In [31]:
print(nil[:5])

[1 2 3 4 5]


# Aritmatik

In [33]:
nil = [4, 4]
nil_square = np.sqrt(nil)

print(nil_square)

[2. 2.]


In [34]:
nil2 = [10, 20, 50, 100]
nil_log = np.log(nil2)

print(nil_log)

[2.30258509 2.99573227 3.91202301 4.60517019]


In [35]:
nil3 = [1, 3, 4]
nil_exp = np.exp(nil3)

print(nil_exp)

[ 2.71828183 20.08553692 54.59815003]


In [37]:
nil4 = [30, 45, 60, 90]
np_sin = np.sin(nil4)

print(np_sin)

[-0.98803162  0.85090352 -0.30481062  0.89399666]


In [38]:
np_cos = np.cos(nil4)

print(np_cos)

[ 0.15425145  0.52532199 -0.95241298 -0.44807362]


# Linear Algebra

In [39]:
A = np.random.randn(2,3)
B = np.random.randn(3,2)

In [41]:
print(A)
print("------------------")
print(B)

[[-0.56857714 -0.92186898 -0.01698934]
 [ 2.89860726  1.13565601 -0.08665939]]
------------------
[[ 0.1617186  -0.28762961]
 [-0.80917908 -0.01060797]
 [-2.21996351 -0.43601532]]


In [42]:
hsl_kali = np.dot(A,B)

print(hsl_kali)

[[ 0.6917233   0.18072639]
 [-0.25780968 -0.80798746]]


In [43]:
hsl_kali2 = np.dot(B,A)

print(hsl_kali2)

[[-0.92567477 -0.47573166  0.02217831]
 [ 0.42933237  0.73391008  0.0146667 ]
 [-0.00161666  1.55135209  0.07550053]]


In [44]:
baris1 = [1, 2, 3]
baris2 = [4, 5, 6]
baris3 = [7, 8, 9]

ar_2d = np.array([baris1, baris2, baris3])
multiply = np.multiply(ar_2d, ar_2d)

print(multiply)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [45]:
baris1 = [1, 2]
baris2 = [3, 4]

ar_2d_2 = np.array([baris1, baris2])
inverse = np.linalg.inv(ar_2d_2)

print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [49]:
baris1 = [1, 2, 3, 4]
baris2 = [4, 5, 6, 7]
baris3 = [7, 8, 9, 10]
baris4 = [11, 12, 13, 14]

ar_2d_3 = np.array([baris1, baris2, baris3, baris4])
determinan = np.linalg.det(ar_2d_3)

print(determinan)

1.5777218104420312e-29


In [50]:
trace = np.trace(ar_2d_3)

In [51]:
print(trace)

29
